 # This is a basic workflow to help you get started with Actions

name: Email list of completed Jira Tasks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    -  main
  # schedule:
  # - cron: "0 0 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: Nonsense variable for it to work
        required: false
        default: 'DoctorGenius'

jobs:
  sendsns:
    runs-on: ubuntu-latest
    steps:
      - name: sendsns
        run: |
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:303278963359:testing-jf" --message '{"name":"John", "location":"Ontario"}' --region us-east-1
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  notify:
    runs-on: ubuntu-latest
    steps:
#      - name: install AWS CLI
#        run: |
#          curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
#          chmod +x install-aws.sh
#          ./install-aws.sh "v2" "amd64"
#          rm install-aws.sh

#       - name: install AWS CLI
#         id: install-aws-cli
#         uses: unfor19/install-aws-cli-action@v1.0.3
#         with:
#           version: 2     # default
#           verbose: false # default
#           arch: amd64    # allowed values: amd64, arm64
          
      - name: clone repo
        uses: actions/checkout@v3

      - name: Fetch all merges to branch since last mid-night
        run: |
          git log --merges --since="1 day" > message

      - name: Publish merges to SNS Topic
        uses: nothingalike/sns-publish-topic@v1.6
        with:
          MESSAGE: $(cat message)
          TOPIC_ARN: "arn:aws:sns:us-east-1:303278963359:testing-jf"

        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
